Verify if a volume is active.
tighten/takeout pull request #129
Opened 2020-09-18 11:04 UTC by danielebarbaro

Hi @mattstauffer , this maybe solve #123 .

I used "maybe" because I've a doubt. 
At the moment I checked with `docker ps -a --filter volume=volume_name` that a volume exist and the result is:
![Screenshot 2020-09-18 at 12 37 55](https://user-images.githubusercontent.com/4376886/93588696-0dd55f80-f9ac-11ea-9964-36a023698426.png)

So when user chose an existing container takeout return an error until user chose a unique name container.

Do you want to handle ,in some way, also this behaviour?

![Screenshot 2020-09-18 at 12 38 09](https://user-images.githubusercontent.com/4376886/93588835-407f5800-f9ac-11ea-81d1-8bb8b0189510.png)

2020-09-26 02:56 UTC, mattstauffer commented
I think the second screenshot's behavior is the target of #89, so we can ignore that for this PR. Reviewing the rest of the PR now. Thanks!

2020-09-26 02:58 UTC, mattstauffer requested changes
Great work! Just a few quick notes

2020-09-26 02:58 UTC, mattstauffer commented on app/Shell/Docker.php
> +    public function usedVolumes(string $volumeName): Collection
We can drop this, since it's not used, right?

2020-09-26 02:58 UTC, mattstauffer commented on app/Shell/Docker.php
> +    protected function isVolumeUsedRawOutput(string $volumeName): string
What if we rename this `listMatchingVolumesRawOutput`?

2020-09-26 10:10 UTC, danielebarbaro commented
Hi @mattstauffer , thanks for your review. A made some review and a merge main in my branch to avoid conflicts.

2020-10-08 07:25 UTC, danielebarbaro commented
Hi @mattstauffer now PR is updated.
All tests pass.

This PR needs #157 .

2020-10-12 19:50 UTC, mattstauffer commented
@danielebarbaro Great--taking a look now. Thanks!

2020-10-12 19:51 UTC, merged

2020-10-12 19:51 UTC, mattstauffer commented
Looks great. Thanks so much @danielebarbaro!