Using --default option
tighten/takeout pull request #133
Opened 2020-09-23 20:37 UTC by khanalpride

I have worked out on using --default on any enable command to use default ports and tags or keys

can be useful if you create many services at once as per your project setup
#130 

I have edited the Environment.php to check ports availability on Linux and WSL
And I have edited the container name, so that it will not conflict when creating 2 docker container with same version but with different ports

2020-09-24 03:08 UTC, khanalpride commented
@mattstauffer all tests pass on local.
And yeah it was difficult to add tests. :(

2020-09-25 23:30 UTC, josecanhelp commented
@khanalpride Thanks so much for this PR. I'm still working through a few adjustments I'd like to make. Mainly, I was hoping to use a `-y` flag instead of `--default`, but I can't remember if this was possible with Laravel Zero. If you can figure it out, please add it to the PR. Otherwise, I'll get this merged in after I figure it out.

Great work!

2020-09-26 03:17 UTC, khanalpride commented
@josecanhelp sure.
i will check that out.
thanks.

2020-09-28 14:56 UTC, khanalpride commented
@josecanhelp I am still trying to find way for `-y` flag.

May be @nunomaduro  can provide some clue regarding `-y` flag here. So I can implement it.

2020-09-28 16:52 UTC, khanalpride commented
@josecanhelp  just added --all to disable command
so we can disable all docker container using just
`takeout disable --all`

2020-10-06 03:26 UTC, khanalpride commented
@josecanhelp @mattstauffer 
This PR has no response? Is it being considered?
Or it needs more work?

2020-10-06 06:41 UTC, josecanhelp commented
Hey @khanalpride sorry for the delay. I am still considering this PR, but I just haven't had the time to review it. I will update you soon. Thanks again for this work!

2020-10-07 07:09 UTC, josecanhelp requested changes
I had a few requests, but this is really great work! I can't wait to get it merged in and deployed.

Thank you.

2020-10-07 07:09 UTC, josecanhelp commented on app/Shell/Environment.php
> +        $process = $this->shell->execQuietly("{$netstatCmd} -vanp tcp | grep '{$portText}' | grep -v 'TIME_WAIT' | grep -v 'CLOSE_WAIT' | grep -v 'FIN_WAIT'");
I super appreciate the help with cross-platform stuff. Like before, it's much easier to review and test a PR when it has a single feature. Let's leave this in and I'll run tests on WSL.

2020-10-07 07:12 UTC, josecanhelp commented
Another request would be to only have 2 dashes between before the port number in the container name: 
![image](https://user-images.githubusercontent.com/2329654/95298988-c830e780-0831-11eb-91d2-c5dfef47cc9b.png)

2020-10-07 17:17 UTC, khanalpride commented
@josecanhelp I have checked and reviewed your suggestion.
Please check and let me know. :)

2020-10-08 05:27 UTC, josecanhelp approved these changes
Again, great work on this! 👏

2020-10-08 05:27 UTC, merged