Added clickhouse support
tighten/takeout pull request #159
Opened 2020-10-12 19:44 UTC by K03413R

Added clickhouse support

2020-11-09 16:00 UTC, mattstauffer requested changes

2020-11-09 16:00 UTC, mattstauffer commented on app/Services/ClickHouse.php
> +            'prompt' => 'Which http host port would you like to use?',
```suggestion
            'prompt' => 'Which HTTP host port would you like to use?',
```

2020-11-13 15:58 UTC, mattstauffer commented on app/Services/ClickHouse.php
> +
You'll need to pull in the latest changes from master in order to run the correct PHPCS settings.

2020-12-01 22:04 UTC, merged

2020-12-01 22:13 UTC, grantjanecek commented on app/Services/ClickHouse.php
> +
@mattstauffer sorry this fell off my radar.